- id: '1589788169492'
  alias: Switch - Turn off Lamp
  description: ''
  initial_state: true
  trigger:
  - event_data:
      event: 1002
      id: smart_switch
    event_type: deconz_event
    platform: event
  action:
  - entity_id: light.zha_office_light
    service: light.toggle
- id: '1589788614432'
  alias: New Automation
  description: ''
  trigger:
  - event_data:
      event: 1002
      id: smart_switch
    event_type: deconz_event
    platform: event
  condition:
  - condition: state
    entity_id: media_player.bedroom_sonos
    state: playing
  action:
  - data: {}
    entity_id: media_player.bedroom_sonos
    service: media_player.media_stop
- id: '1589789047507'
  alias: New Automation
  description: ''
  trigger:
  - device_id: b08ad3d565af4d56b400814a5ec32438
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_short_press
  condition: []
  action:
  - device_id: 1e270c99731d4e31b6d49ee98267d65b
    domain: light
    entity_id: light.all_lights
    type: turn_off
- id: '1589789139850'
  alias: New Automation
  description: ''
  trigger:
  - device_id: b08ad3d565af4d56b400814a5ec32438
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_short_release
  condition: []
  action:
  - device_id: 78410edeab60411794fc4e561f8f57ef
    domain: light
    entity_id: light.all_lights_2
    type: turn_off
