---
###
### Allow changes to log level from UI
### Based on https://github.com/whatdaybob/Home-assistant-config/blob/master/config/packages/logger_set_levels.yaml
###

automation:
  - id: logger_setdefaultlevel
    alias: Logger - Set Default Level
    trigger:
      - platform: state
        entity_id: input_select.log_level
    action:
      service: logger.set_default_level
      data_template:
        level: "{{ states('input_select.log_level') }}"

input_select:
  log_level:
    name: Log Level
    options:
      - critical
      - fatal
      - error
      - warning
      - warn
      - info
      - debug
      - notset
    initial: warning
