# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/house_information.html

house_information:
  favorites:
      - entity: sensor.binday_next
        icon_on: mdi:truck-delivery
        icon_off: mdi:truck-delivery
      - entity: sensor.netatmo_brisbane_street_rain_sum_rain_24
        icon_on: mdi:weather-rainy
        icon_off: mdi:weather-rainy
      - entity: sensor.bom_tamworth_rain_today
        icon_on: mdi:weather-rainy
        icon_off: mdi:weather-rainy
  #   - entity: binary_sensor.doorbell_button
  #     icon_on: fas:bell
  #     icon_off: fas:bell
  #   - entity: binary_sensor.hallway_door_contact
  #     icon_on: fas:door-open
  #     icon_off: fas:door-closed

  calendar:
    - calendar.sydney_swans
    - calendar.supercars
    - calendar.newcastle_knights