# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/persons.html

persons:
  - name: Thomas
    track: person.thomas_baxter
    picture_path: 'images/persons/avatar_thomas.jpg'
    show_map: true
    # addons:
    #   - name: Hello person
    #     icon: fas:puzzle-piece
    #     path: 'dwains-theme/addons/persons/hello-person/page.yaml'
    #     data:
    #       some_data: 'This is some data parsed.'
    #       some_other_data: 'and some other data.'
    # more_entities:
    #   columns: 1 #optional
    #   entities:
    page_entities:
      columns: 1 #optional
      entities:
        - entity: sensor.activity_2
        - entity: sensor.average_active_pace
        - entity: sensor.battery_level_2
        - entity: sensor.battery_state_2
        - entity: sensor.bssid_2
        - entity: sensor.connection_type_2
        - entity: sensor.distance
        - entity: sensor.floors_ascended
        - entity: sensor.floors_descended
        - entity: sensor.geocoded_location_2
        - entity: sensor.last_update_trigger_2
        - entity: sensor.sim_1
        - entity: sensor.tbiphone11_sim_2
        - entity: sensor.ssid_2
        - entity: sensor.steps