---
sensor:
  - platform: snmp
    host: !secret unifi_switch_hateful8_ipaddress
    name: unifiswitch_hateful8_uptime
    baseoid: 1.3.6.1.2.1.1.3.0
    value_template: >
      {%- set time = value | int // 100 %}
      {%- set minutes = ((time % 3600) // 60) %}
      {%- set minutes = '{}min'.format(minutes) if minutes > 0 else '' %}
      {%- set hours = ((time % 86400) // 3600) %}
      {%- set hours = '{}hr '.format(hours) if hours > 0 else '' %}
      {%- set days = (time // 86400) %}
      {%- set days = '{}d '.format(days) if days > 0 else '' %}
      {{ 'Less than 1 min' if time < 60 else days + hours + minutes }}

# Port Speed
  - platform: snmp
    host: !secret unifi_switch_hateful8_ipaddress
    name: unifiswitch_hateful8_port1_speed
    baseoid: 1.3.6.1.2.1.2.2.1.5.1
    unit_of_measurement: 'Mbps'
    value_template: >
      {%- set val = value | int // 1000000 %}
      {{ val }}

  - platform: snmp
    host: !secret unifi_switch_hateful8_ipaddress
    name: unifiswitch_hateful8_port2_speed
    baseoid: 1.3.6.1.2.1.2.2.1.5.2
    unit_of_measurement: 'Mbps'
    value_template: >
      {%- set val = value | int // 1000000 %}
      {{ val }}

  - platform: snmp
    host: !secret unifi_switch_hateful8_ipaddress
    name: unifiswitch_hateful8_port3_speed
    baseoid: 1.3.6.1.2.1.2.2.1.5.3
    unit_of_measurement: 'Mbps'
    value_template: >
      {%- set val = value | int // 1000000 %}
      {{ val }}

  - platform: snmp
    host: !secret unifi_switch_hateful8_ipaddress
    name: unifiswitch_hateful8_port4_speed
    baseoid: 1.3.6.1.2.1.2.2.1.5.4
    unit_of_measurement: 'Mbps'
    value_template: >
      {%- set val = value | int // 1000000 %}
      {{ val }}

  - platform: snmp
    host: !secret unifi_switch_hateful8_ipaddress
    name: unifiswitch_hateful8_port5_speed
    baseoid: 1.3.6.1.2.1.2.2.1.5.5
    unit_of_measurement: 'Mbps'
    value_template: >
      {%- set val = value | int // 1000000 %}
      {{ val }}

  - platform: snmp
    host: !secret unifi_switch_hateful8_ipaddress
    name: unifiswitch_hateful8_port6_speed
    baseoid: 1.3.6.1.2.1.2.2.1.5.6
    unit_of_measurement: 'Mbps'
    value_template: >
      {%- set val = value | int // 1000000 %}
      {{ val }}

  - platform: snmp
    host: !secret unifi_switch_hateful8_ipaddress
    name: unifiswitch_hateful8_port7_speed
    baseoid: 1.3.6.1.2.1.2.2.1.5.7
    unit_of_measurement: 'Mbps'
    value_template: >
      {%- set val = value | int // 1000000 %}
      {{ val }}

  - platform: snmp
    host: !secret unifi_switch_hateful8_ipaddress
    name: unifiswitch_hateful8_port8_speed
    baseoid: 1.3.6.1.2.1.2.2.1.5.8
    unit_of_measurement: 'Mbps'
    value_template: >
      {%- set val = value | int // 1000000 %}
      {{ val }}
