---
# {% for state in states.binary_sensor if 'ha_dockermon' in state.entity_id %}
#   {% set string = state.entity_id.split('.')[1] %}
#   {% set server = string.split('_')[0] %}
#   {% set container = string.replace(server + "_ha_dockermon_","") %}
#   status_{{server}}_docker_{{container}}:
#     friendly_name: Status - {{server}} Docker {{container}}
#     entity_id: binary_sensor.{{server}}_ha_dockermon_{{container}}
#     value_template: >-
#       {%raw%}{% if is_state('binary_sensor.{%endraw%}{{server}}{%raw%}_ha_dockermon_{%endraw%}{{container}}{%raw%}', 'on') %}
#        100
#       {% elif is_state('binary_sensor.{%endraw%}{{server}}{%raw%}_ha_dockermon_{%endraw%}{{container}}{%raw%}', 'off') %}
#        0
#       {% endif %}{%endraw%}{% endfor %}
sensor:
  - platform: template
    sensors:
      status_vmtbsh03_docker_addon_15ef4d2f_esphome:
        friendly_name: Status - vmtbsh03 Docker addon_15ef4d2f_esphome
        entity_id: binary_sensor.vmtbsh03_ha_dockermon_addon_15ef4d2f_esphome
        value_template: >-
          {% if is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_15ef4d2f_esphome', 'on') %}
          100
          {% elif is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_15ef4d2f_esphome', 'off') %}
          0
          {% endif %}

      status_vmtbsh03_docker_addon_41cba666_xboxone:
        friendly_name: Status - vmtbsh03 Docker addon_41cba666_xboxone
        entity_id: binary_sensor.vmtbsh03_ha_dockermon_addon_41cba666_xboxone
        value_template: >-
          {% if is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_41cba666_xboxone', 'on') %}
          100
          {% elif is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_41cba666_xboxone', 'off') %}
          0
          {% endif %}

      status_vmtbsh03_docker_addon_a0d7b954_adb:
        friendly_name: Status - vmtbsh03 Docker addon_a0d7b954_adb
        entity_id: binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_adb
        value_template: >-
          {% if is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_adb', 'on') %}
          100
          {% elif is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_adb', 'off') %}
          0
          {% endif %}

      status_vmtbsh03_docker_addon_a0d7b954_airsonos:
        friendly_name: Status - vmtbsh03 Docker addon_a0d7b954_airsonos
        entity_id: binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_airsonos
        value_template: >-
          {% if is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_airsonos', 'on') %}
          100
          {% elif is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_airsonos', 'off') %}
          0
          {% endif %}

      status_vmtbsh03_docker_addon_a0d7b954_appdaemon:
        friendly_name: Status - vmtbsh03 Docker addon_a0d7b954_appdaemon
        entity_id: binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_appdaemon
        value_template: >-
          {% if is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_appdaemon', 'on') %}
          100
          {% elif is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_appdaemon', 'off') %}
          0
          {% endif %}

      status_vmtbsh03_docker_addon_a0d7b954_glances:
        friendly_name: Status - vmtbsh03 Docker addon_a0d7b954_glances
        entity_id: binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_glances
        value_template: >-
          {% if is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_glances', 'on') %}
          100
          {% elif is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_glances', 'off') %}
          0
          {% endif %}

      status_vmtbsh03_docker_addon_a0d7b954_jupyterlablite:
        friendly_name: Status - vmtbsh03 Docker addon_a0d7b954_jupyterlablite
        entity_id: binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_jupyterlablite
        value_template: >-
          {% if is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_jupyterlablite', 'on') %}
          100
          {% elif is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_jupyterlablite', 'off') %}
          0
          {% endif %}

      status_vmtbsh03_docker_addon_a0d7b954_nodered:
        friendly_name: Status - vmtbsh03 Docker addon_a0d7b954_nodered
        entity_id: binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_nodered
        value_template: >-
          {% if is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_nodered', 'on') %}
          100
          {% elif is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_nodered', 'off') %}
          0
          {% endif %}

      status_vmtbsh03_docker_addon_a0d7b954_portainer:
        friendly_name: Status - vmtbsh03 Docker addon_a0d7b954_portainer
        entity_id: binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_portainer
        value_template: >-
          {% if is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_portainer', 'on') %}
          100
          {% elif is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_portainer', 'off') %}
          0
          {% endif %}

      status_vmtbsh03_docker_addon_a0d7b954_ssh:
        friendly_name: Status - vmtbsh03 Docker addon_a0d7b954_ssh
        entity_id: binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_ssh
        value_template: >-
          {% if is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_ssh', 'on') %}
          100
          {% elif is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_ssh', 'off') %}
          0
          {% endif %}

      status_vmtbsh03_docker_addon_a0d7b954_vscode:
        friendly_name: Status - vmtbsh03 Docker addon_a0d7b954_vscode
        entity_id: binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_vscode
        value_template: >-
          {% if is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_vscode', 'on') %}
          100
          {% elif is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_a0d7b954_vscode', 'off') %}
          0
          {% endif %}

      status_vmtbsh03_docker_addon_cebe7a76_hassio_google_drive_backup:
        friendly_name: Status - vmtbsh03 Docker addon_cebe7a76_hassio_google_drive_backup
        entity_id: binary_sensor.vmtbsh03_ha_dockermon_addon_cebe7a76_hassio_google_drive_backup
        value_template: >-
          {% if is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_cebe7a76_hassio_google_drive_backup', 'on') %}
          100
          {% elif is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_cebe7a76_hassio_google_drive_backup', 'off') %}
          0
          {% endif %}

      status_vmtbsh03_docker_addon_core_mariadb:
        friendly_name: Status - vmtbsh03 Docker addon_core_mariadb
        entity_id: binary_sensor.vmtbsh03_ha_dockermon_addon_core_mariadb
        value_template: >-
          {% if is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_core_mariadb', 'on') %}
          100
          {% elif is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_core_mariadb', 'off') %}
          0
          {% endif %}

      status_vmtbsh03_docker_addon_core_mosquitto:
        friendly_name: Status - vmtbsh03 Docker addon_core_mosquitto
        entity_id: binary_sensor.vmtbsh03_ha_dockermon_addon_core_mosquitto
        value_template: >-
          {% if is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_core_mosquitto', 'on') %}
          100
          {% elif is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_core_mosquitto', 'off') %}
          0
          {% endif %}

      status_vmtbsh03_docker_addon_core_samba:
        friendly_name: Status - vmtbsh03 Docker addon_core_samba
        entity_id: binary_sensor.vmtbsh03_ha_dockermon_addon_core_samba
        value_template: >-
          {% if is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_core_samba', 'on') %}
          100
          {% elif is_state('binary_sensor.vmtbsh03_ha_dockermon_addon_core_samba', 'off') %}
          0
          {% endif %}

      status_vmtbsh03_docker_ha_dockermon:
        friendly_name: Status - vmtbsh03 Docker ha_dockermon
        entity_id: binary_sensor.vmtbsh03_ha_dockermon_ha_dockermon
        value_template: >-
          {% if is_state('binary_sensor.vmtbsh03_ha_dockermon_ha_dockermon', 'on') %}
          100
          {% elif is_state('binary_sensor.vmtbsh03_ha_dockermon_ha_dockermon', 'off') %}
          0
          {% endif %}

      status_vmtbsh03_docker_hassio_audio:
        friendly_name: Status - vmtbsh03 Docker hassio_audio
        entity_id: binary_sensor.vmtbsh03_ha_dockermon_hassio_audio
        value_template: >-
          {% if is_state('binary_sensor.vmtbsh03_ha_dockermon_hassio_audio', 'on') %}
          100
          {% elif is_state('binary_sensor.vmtbsh03_ha_dockermon_hassio_audio', 'off') %}
          0
          {% endif %}

      status_vmtbsh03_docker_hassio_cli:
        friendly_name: Status - vmtbsh03 Docker hassio_cli
        entity_id: binary_sensor.vmtbsh03_ha_dockermon_hassio_cli
        value_template: >-
          {% if is_state('binary_sensor.vmtbsh03_ha_dockermon_hassio_cli', 'on') %}
          100
          {% elif is_state('binary_sensor.vmtbsh03_ha_dockermon_hassio_cli', 'off') %}
          0
          {% endif %}

      status_vmtbsh03_docker_hassio_dns:
        friendly_name: Status - vmtbsh03 Docker hassio_dns
        entity_id: binary_sensor.vmtbsh03_ha_dockermon_hassio_dns
        value_template: >-
          {% if is_state('binary_sensor.vmtbsh03_ha_dockermon_hassio_dns', 'on') %}
          100
          {% elif is_state('binary_sensor.vmtbsh03_ha_dockermon_hassio_dns', 'off') %}
          0
          {% endif %}

      status_vmtbsh03_docker_hassio_multicast:
        friendly_name: Status - vmtbsh03 Docker hassio_multicast
        entity_id: binary_sensor.vmtbsh03_ha_dockermon_hassio_multicast
        value_template: >-
          {% if is_state('binary_sensor.vmtbsh03_ha_dockermon_hassio_multicast', 'on') %}
          100
          {% elif is_state('binary_sensor.vmtbsh03_ha_dockermon_hassio_multicast', 'off') %}
          0
          {% endif %}

      status_vmtbsh03_docker_hassio_supervisor:
        friendly_name: Status - vmtbsh03 Docker hassio_supervisor
        entity_id: binary_sensor.vmtbsh03_ha_dockermon_hassio_supervisor
        value_template: >-
          {% if is_state('binary_sensor.vmtbsh03_ha_dockermon_hassio_supervisor', 'on') %}
          100
          {% elif is_state('binary_sensor.vmtbsh03_ha_dockermon_hassio_supervisor', 'off') %}
          0
          {% endif %}

      status_vmtbsh03_docker_hassos_supervisor:
        friendly_name: Status - vmtbsh03 Docker hassos_supervisor
        entity_id: binary_sensor.vmtbsh03_ha_dockermon_hassos_supervisor
        value_template: >-
          {% if is_state('binary_sensor.vmtbsh03_ha_dockermon_hassos_supervisor', 'on') %}
          100
          {% elif is_state('binary_sensor.vmtbsh03_ha_dockermon_hassos_supervisor', 'off') %}
          0
          {% endif %}

      status_vmtbsh03_docker_homeassistant:
        friendly_name: Status - vmtbsh03 Docker homeassistant
        entity_id: binary_sensor.vmtbsh03_ha_dockermon_homeassistant
        value_template: >-
          {% if is_state('binary_sensor.vmtbsh03_ha_dockermon_homeassistant', 'on') %}
          100
          {% elif is_state('binary_sensor.vmtbsh03_ha_dockermon_homeassistant', 'off') %}
          0
          {% endif %}
