---
sensor:
  # {% for n in range(12) %}{% set u = n + 1 %}{% set l = state_attr('sensor.radarr_upcoming_media', 'data')| count -1 %}
  #   lovelace_radarr_upcoming_{{'%02d' % (u)}}:
  #     friendly_name: Lovelace - Radarr Upcoming {{'%02d' % (u)}}
  #     entity_id: sensor.radarr_upcoming_media
  #     value_template: >
  #       {% raw %}{{state_attr('sensor.radarr_upcoming_media', 'data')[{%endraw%}{{u}}{%raw%}]['title'] if {%endraw%}{{u}}{%raw%} <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}{% endraw %}
  #     attribute_templates:
  #       name: >
  #         {% raw %}{{state_attr('sensor.radarr_upcoming_media', 'data')[{%endraw%}{{u}}{%raw%}]['title'] if {%endraw%}{{u}}{%raw%} <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}{% endraw %}
  #       date: >
  #         {% raw %}{{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[{%endraw%}{{u}}{%raw%}]['airdate'])
  #         | timestamp_custom ('%A %-d %b, %H:%M') if {%endraw%}{{u}}{%raw%} <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}{% endraw %}
  #       poster: >
  #         {% raw %}{{state_attr('sensor.radarr_upcoming_media', 'data')[{%endraw%}{{u}}{%raw%}]['poster'] if {%endraw%}{{u}}{%raw%} <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}{% endraw %}
  #       downloaded: >
  #         {% raw %}{{state_attr('sensor.radarr_upcoming_media', 'data')[{%endraw%}{{u}}{%raw%}]['flag'] if {%endraw%}{{u}}{%raw%} <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}{% endraw %}
  #       onairtoday: >
  #         {% raw %}{{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[{%endraw%}{{u}}{%raw%}]['airdate'])
  #         | timestamp_custom ('%Y/%m/%d') == as_timestamp(now())
  #         | timestamp_custom ('%Y/%m/%d') if {%endraw%}{{u}}{%raw%} <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}{% endraw %}
  #   {% endfor %}
  - platform: template
    sensors:
      lovelace_radarr_upcoming_01:
        friendly_name: Lovelace - Radarr Upcoming 01
        entity_id: sensor.radarr_upcoming_media
        value_template: >
          {{state_attr('sensor.radarr_upcoming_media', 'data')[1]['title'] if 1 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}
        attribute_templates:
          name: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[1]['title'] if 1 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}
          date: >
            {{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[1]['airdate']) 
            | timestamp_custom ('%A %-d %b, %H:%M') if 1 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          poster: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[1]['poster'] if 1 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          downloaded: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[1]['flag'] if 1 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          onairtoday: >
            {{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[1]['airdate']) 
            | timestamp_custom ('%Y/%m/%d') == as_timestamp(now())
            | timestamp_custom ('%Y/%m/%d') if 1 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}

      lovelace_radarr_upcoming_02:
        friendly_name: Lovelace - Radarr Upcoming 02
        entity_id: sensor.radarr_upcoming_media
        value_template: >
          {{state_attr('sensor.radarr_upcoming_media', 'data')[2]['title'] if 2 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}
        attribute_templates:
          name: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[2]['title'] if 2 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}
          date: >
            {{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[2]['airdate']) 
            | timestamp_custom ('%A %-d %b, %H:%M') if 2 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          poster: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[2]['poster'] if 2 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          downloaded: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[2]['flag'] if 2 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          onairtoday: >
            {{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[2]['airdate']) 
            | timestamp_custom ('%Y/%m/%d') == as_timestamp(now())
            | timestamp_custom ('%Y/%m/%d') if 2 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}

      lovelace_radarr_upcoming_03:
        friendly_name: Lovelace - Radarr Upcoming 03
        entity_id: sensor.radarr_upcoming_media
        value_template: >
          {{state_attr('sensor.radarr_upcoming_media', 'data')[3]['title'] if 3 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}
        attribute_templates:
          name: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[3]['title'] if 3 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}
          date: >
            {{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[3]['airdate']) 
            | timestamp_custom ('%A %-d %b, %H:%M') if 3 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          poster: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[3]['poster'] if 3 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          downloaded: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[3]['flag'] if 3 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          onairtoday: >
            {{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[3]['airdate']) 
            | timestamp_custom ('%Y/%m/%d') == as_timestamp(now())
            | timestamp_custom ('%Y/%m/%d') if 3 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}

      lovelace_radarr_upcoming_04:
        friendly_name: Lovelace - Radarr Upcoming 04
        entity_id: sensor.radarr_upcoming_media
        value_template: >
          {{state_attr('sensor.radarr_upcoming_media', 'data')[4]['title'] if 4 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}
        attribute_templates:
          name: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[4]['title'] if 4 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}
          date: >
            {{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[4]['airdate']) 
            | timestamp_custom ('%A %-d %b, %H:%M') if 4 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          poster: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[4]['poster'] if 4 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          downloaded: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[4]['flag'] if 4 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          onairtoday: >
            {{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[4]['airdate']) 
            | timestamp_custom ('%Y/%m/%d') == as_timestamp(now())
            | timestamp_custom ('%Y/%m/%d') if 4 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}

      lovelace_radarr_upcoming_05:
        friendly_name: Lovelace - Radarr Upcoming 05
        entity_id: sensor.radarr_upcoming_media
        value_template: >
          {{state_attr('sensor.radarr_upcoming_media', 'data')[5]['title'] if 5 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}
        attribute_templates:
          name: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[5]['title'] if 5 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}
          date: >
            {{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[5]['airdate']) 
            | timestamp_custom ('%A %-d %b, %H:%M') if 5 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          poster: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[5]['poster'] if 5 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          downloaded: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[5]['flag'] if 5 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          onairtoday: >
            {{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[5]['airdate']) 
            | timestamp_custom ('%Y/%m/%d') == as_timestamp(now())
            | timestamp_custom ('%Y/%m/%d') if 5 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}

      lovelace_radarr_upcoming_06:
        friendly_name: Lovelace - Radarr Upcoming 06
        entity_id: sensor.radarr_upcoming_media
        value_template: >
          {{state_attr('sensor.radarr_upcoming_media', 'data')[6]['title'] if 6 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}
        attribute_templates:
          name: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[6]['title'] if 6 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}
          date: >
            {{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[6]['airdate']) 
            | timestamp_custom ('%A %-d %b, %H:%M') if 6 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          poster: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[6]['poster'] if 6 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          downloaded: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[6]['flag'] if 6 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          onairtoday: >
            {{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[6]['airdate']) 
            | timestamp_custom ('%Y/%m/%d') == as_timestamp(now())
            | timestamp_custom ('%Y/%m/%d') if 6 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}

      lovelace_radarr_upcoming_07:
        friendly_name: Lovelace - Radarr Upcoming 07
        entity_id: sensor.radarr_upcoming_media
        value_template: >
          {{state_attr('sensor.radarr_upcoming_media', 'data')[7]['title'] if 7 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}
        attribute_templates:
          name: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[7]['title'] if 7 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}
          date: >
            {{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[7]['airdate']) 
            | timestamp_custom ('%A %-d %b, %H:%M') if 7 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          poster: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[7]['poster'] if 7 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          downloaded: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[7]['flag'] if 7 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          onairtoday: >
            {{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[7]['airdate']) 
            | timestamp_custom ('%Y/%m/%d') == as_timestamp(now())
            | timestamp_custom ('%Y/%m/%d') if 7 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}

      lovelace_radarr_upcoming_08:
        friendly_name: Lovelace - Radarr Upcoming 08
        entity_id: sensor.radarr_upcoming_media
        value_template: >
          {{state_attr('sensor.radarr_upcoming_media', 'data')[8]['title'] if 8 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}
        attribute_templates:
          name: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[8]['title'] if 8 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}
          date: >
            {{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[8]['airdate']) 
            | timestamp_custom ('%A %-d %b, %H:%M') if 8 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          poster: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[8]['poster'] if 8 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          downloaded: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[8]['flag'] if 8 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          onairtoday: >
            {{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[8]['airdate']) 
            | timestamp_custom ('%Y/%m/%d') == as_timestamp(now())
            | timestamp_custom ('%Y/%m/%d') if 8 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}

      lovelace_radarr_upcoming_09:
        friendly_name: Lovelace - Radarr Upcoming 09
        entity_id: sensor.radarr_upcoming_media
        value_template: >
          {{state_attr('sensor.radarr_upcoming_media', 'data')[9]['title'] if 9 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}
        attribute_templates:
          name: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[9]['title'] if 9 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}
          date: >
            {{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[9]['airdate']) 
            | timestamp_custom ('%A %-d %b, %H:%M') if 9 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          poster: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[9]['poster'] if 9 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          downloaded: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[9]['flag'] if 9 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          onairtoday: >
            {{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[9]['airdate']) 
            | timestamp_custom ('%Y/%m/%d') == as_timestamp(now())
            | timestamp_custom ('%Y/%m/%d') if 9 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}

      lovelace_radarr_upcoming_10:
        friendly_name: Lovelace - Radarr Upcoming 10
        entity_id: sensor.radarr_upcoming_media
        value_template: >
          {{state_attr('sensor.radarr_upcoming_media', 'data')[10]['title'] if 10 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}
        attribute_templates:
          name: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[10]['title'] if 10 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}
          date: >
            {{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[10]['airdate']) 
            | timestamp_custom ('%A %-d %b, %H:%M') if 10 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          poster: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[10]['poster'] if 10 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          downloaded: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[10]['flag'] if 10 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          onairtoday: >
            {{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[10]['airdate']) 
            | timestamp_custom ('%Y/%m/%d') == as_timestamp(now())
            | timestamp_custom ('%Y/%m/%d') if 10 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}

      lovelace_radarr_upcoming_11:
        friendly_name: Lovelace - Radarr Upcoming 11
        entity_id: sensor.radarr_upcoming_media
        value_template: >
          {{state_attr('sensor.radarr_upcoming_media', 'data')[11]['title'] if 11 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}
        attribute_templates:
          name: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[11]['title'] if 11 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}
          date: >
            {{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[11]['airdate']) 
            | timestamp_custom ('%A %-d %b, %H:%M') if 11 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          poster: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[11]['poster'] if 11 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          downloaded: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[11]['flag'] if 11 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          onairtoday: >
            {{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[11]['airdate']) 
            | timestamp_custom ('%Y/%m/%d') == as_timestamp(now())
            | timestamp_custom ('%Y/%m/%d') if 11 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}

      lovelace_radarr_upcoming_12:
        friendly_name: Lovelace - Radarr Upcoming 12
        entity_id: sensor.radarr_upcoming_media
        value_template: >
          {{state_attr('sensor.radarr_upcoming_media', 'data')[12]['title'] if 12 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}
        attribute_templates:
          name: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[12]['title'] if 12 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else 'None'}}
          date: >
            {{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[12]['airdate']) 
            | timestamp_custom ('%A %-d %b, %H:%M') if 12 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          poster: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[12]['poster'] if 12 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          downloaded: >
            {{state_attr('sensor.radarr_upcoming_media', 'data')[12]['flag'] if 12 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
          onairtoday: >
            {{as_timestamp(state_attr('sensor.radarr_upcoming_media', 'data')[12]['airdate']) 
            | timestamp_custom ('%Y/%m/%d') == as_timestamp(now())
            | timestamp_custom ('%Y/%m/%d') if 12 <= state_attr('sensor.radarr_upcoming_media', 'data')| count -1 else "None"}}
